export const Products = (() => {
  let Item = [
    {
      type: "Lamp",
      id: "T1",
      name: "Spherical Lamp",
      img: "src/assets/TL1.png",
      price: 100,
    },
  ];
  let data = [
    {
      type: "Lamp",
      id: "T1",
      name: "Spherical Lamp",
      img: "src/assets/TL1.png",
      imgs: "src/assets/TL11.png",
      price: 100,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero reiciendis necessitatibus quidem? Fugit ipsam aperiam labore officiis vel nihil eligendi nobis voluptate ex, inventore atque impedit quis, ratione quo. Quibusdam.",
    },
    {
      id: "T2",
      type: "Lamp",
      name: "Vintage Wooden Lamp",
      img: "src/assets/TL2.png",
      price: 100,
    },
    {
      id: "T3",
      type: "Lamp",
      name: "Cage Lamp",
      img: "src/assets/TL3.png",
      price: 100,
    },
    {
      id: "T4",
      type: "Lamp",
      name: "Flower Vase Lamp",
      img: "src/assets/TL4.png",
      price: 100,
    },
    {
      id: "TL5",
      type: "Lamp",
      name: "Box Lamp",
      img: "src/assets/TL5.png",
      price: 100,
    },
    {
      id: "TL6",
      type: "Lamp",
      name: "Sci-fi Lamp",
      img: "src/assets/TL6.png",
      price: 100,
    },
    {
      id: "TL7",
      type: "Lamp",
      name: "Tiny Decoration Lamp",
      img: "src/assets/TL7.png",
      price: 100,
    },
    {
      id: "TL8",
      type: "Lamp",
      name: "Workshop Lamp",
      img: "src/assets/TL8.png",
      price: 100,
    },
    {
      id: "TL9",
      type: "Lamp",
      name: "Crystal Salt Lamp",
      img: "src/assets/TL9.png",
      price: 100,
    },
    {
      id: "TL10",
      type: "Lamp",
      name: "Table Lamp",
      img: "src/assets/TL10.png",
      price: 100,
    },

    {
      id: "W1",
      type: "Light",
      name: "Wall Light",
      img: "src/assets/WL1.png",
      price: 100,
    },
    {
      id: "W2",
      type: "Light",
      name: "Vintage Celling Light",
      img: "src/assets/WL2.png",
      price: 100,
    },
    {
      id: "W3",
      type: "Light",
      name: "Shade Light",
      img: "src/assets/WL3.png",
      price: 100,
    },
    {
      id: "W4",
      type: "Light",
      name: "Disc Light",
      img: "src/assets/WL4.png",
      price: 100,
    },
    {
      id: "WL5",
      type: "Light",
      name: "Workshop Light",
      img: "src/assets/WL5.png",
      price: 100,
    },
    {
      id: "WL6",
      type: "Light",
      name: "Sci-fi Light",
      img: "src/assets/WL6.png",
      price: 100,
    },
    {
      id: "WL7",
      type: "Light",
      name: "Gold Decoration Light",
      img: "src/assets/WL7.png",
      price: 100,
    },
    {
      id: "WL8",
      type: "Light",
      name: "Workshop Light",
      img: "src/assets/WL8.png",
      price: 100,
    },
    {
      id: "WL9",
      type: "Light",
      name: "CrysWal SalW Light",
      img: "src/assets/WL9.png",
      price: 100,
    },
    {
      id: "WL10",
      type: "Light",
      name: "Wable Light",
      img: "src/src/assets/WL10.png",
      price: 100,
    },
  ];

  return data;
})();
